name: itqan_pos
description: ITQAN POS System
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
